name: Build documentation and pack
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2                                  # default
          packchk-version: 1.3.95                                 # default
          gen-doc-script: ./DoxyGen/gen_doc.sh                    # skipped by default
          check-links-script: ./DoxyGen/check_links.sh            # skipped by default
          doc-path: ./Documentation/html                          # skipped by default
          gen-pack-script: ./gen_pack.sh --no-preprocess          # skipped by default
          gen-pack-output: ./output                               # skipped by default
          gh-pages-branch: gh-pages                               # default
